# Generated by Django 2.1.1 on 2021-01-17 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.TextField()),
                ('company_name', models.CharField(max_length=400)),
                ('job_title', models.CharField(max_length=400)),
                ('job_location', models.CharField(max_length=400)),
                ('job_link', models.CharField(max_length=400)),
                ('job_post', models.CharField(default='2021-01-17', max_length=400)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=400), size=8)),
            ],
        ),
    ]
