# Generated by Django 2.2.13 on 2021-01-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_post',
            field=models.CharField(default='2021-01-18', max_length=400),
        ),
    ]
