# Generated by Django 2.2.13 on 2021-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_post',
            field=models.CharField(default='2021-01-21', max_length=400),
        ),
    ]
