# Generated by Django 2.2.13 on 2021-01-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210121_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
