# Generated by Django 2.2.13 on 2021-01-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210123_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='automated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_post',
            field=models.CharField(default='2021-01-27', max_length=400),
        ),
    ]
